-- Run this in Supabase Dashboard > SQL Editor.
-- Buckets: music-files
-- Tables: profiles, songs

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    name text not null default '',
    email text not null default '',
    role text not null default 'user' check (role in ('user', 'admin')),
    created_at timestamptz not null default now()
);

create table if not exists public.songs (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) on delete set null,
    name text not null,
    artist text not null default '',
    album_path text,
    music_path text,
    album_url text,
    music_url text,
    status text not null default 'pending' check (status in ('pending', 'approved', 'hidden')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists songs_status_index on public.songs(status);
create index if not exists songs_user_id_index on public.songs(user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists songs_set_updated_at on public.songs;
create trigger songs_set_updated_at
before update on public.songs
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, name, email, role)
    values (
        new.id,
        coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1), ''),
        coalesce(new.email, ''),
        'user'
    )
    on conflict (id) do update
    set email = excluded.email,
        name = coalesce(nullif(public.profiles.name, ''), excluded.name);
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and role = 'admin'
    );
$$;

alter table public.profiles enable row level security;
alter table public.songs enable row level security;

drop policy if exists "Profiles can read own row" on public.profiles;
create policy "Profiles can read own row"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id or public.is_admin());

drop policy if exists "Profiles can update own name" on public.profiles;
create policy "Profiles can update own name"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id and role = 'user');

drop policy if exists "Approved songs are public" on public.songs;
create policy "Approved songs are public"
on public.songs
for select
to anon, authenticated
using (status = 'approved');

drop policy if exists "Users can read own songs" on public.songs;
create policy "Users can read own songs"
on public.songs
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Admins can read all songs" on public.songs;
create policy "Admins can read all songs"
on public.songs
for select
to authenticated
using (public.is_admin());

drop policy if exists "Users can submit songs" on public.songs;
create policy "Users can submit songs"
on public.songs
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Admins can update songs" on public.songs;
create policy "Admins can update songs"
on public.songs
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete songs" on public.songs;
create policy "Admins can delete songs"
on public.songs
for delete
to authenticated
using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'music-files',
    'music-files',
    true,
    52428800,
    array[
        'audio/mpeg',
        'audio/mp3',
        'audio/wav',
        'audio/ogg',
        'audio/mp4',
        'audio/aac',
        'audio/flac',
        'image/jpeg',
        'image/png',
        'image/gif',
        'image/webp'
    ]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read music files" on storage.objects;
create policy "Public can read music files"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'music-files');

drop policy if exists "Users can upload own music files" on storage.objects;
create policy "Users can upload own music files"
on storage.objects
for insert
to authenticated
with check (
    bucket_id = 'music-files'
    and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "Owners and admins can delete music files" on storage.objects;
create policy "Owners and admins can delete music files"
on storage.objects
for delete
to authenticated
using (
    bucket_id = 'music-files'
    and (
        (storage.foldername(name))[1] = (select auth.uid())::text
        or public.is_admin()
    )
);

-- After creating your first account, set it as admin manually:
-- update public.profiles set role = 'admin' where email = 'your-email@example.com';
